### PR TITLE
Re-export ReleaseKey and ResourceCleanupException

### LINKED ISSUE #2: Can you please add `ReleaseKey` and `ResourceCleanupException` to the export list?
Also, why does `runResource` not have `Error` effect constraint? Is it not needed if `throwIO`used?

### PR DESCRIPTION
**Pull request by mmhat**
Fixes #2 

I also updated the CI setup and added bindings for `release` and `unprotect`.
@arybczak Maybe we can cut a new release at this point?

### CODE REVIEW

File: src/Effectful/Resource.hs [hunk 1]
```diff
@@ -100,6 +106,17 @@ registerEff release = do
     es1 <- cloneEnv es0
     RI.register' istate $ unEff release es1
 
+-- | A variant of 'R.release' adjusted to work in the 'Eff' monad.
+releaseEff :: Resource :> es => R.ReleaseKey -> Eff es ()
+releaseEff = unsafeEff_ . R.release
+
+-- | A variant of 'R.unprotect' adjusted to work in the 'Eff' monad.
+--
+-- /Note:/ the @release@ action returned will run a clone of the environment it
```
Comment (arybczak) [inline src/Effectful/Resource.hs]: Will it? I don't know what `unprotect` does, but I don't see `cloneEnv` below (unlike in `allocateEff`).

Also, is having `es` and `es'` correct here? Does it make sense to be able to run the returned action in a completely different stack?

**Review by arybczak — COMMENTED** [review]
Please split the CI part into a separate PR.

**Comment by mmhat** [comment]
> Please split the CI part into a separate PR.

I moved the CI part to https://github.com/haskell-effectful/resourcet-effectful/pull/6.

File: src/Effectful/Resource.hs (hunk 1 above)
Comment (mmhat) [reply src/Effectful/Resource.hs]: > Will it? I don't know what `unprotect` does, but I don't see `cloneEnv` below (unlike in `allocateEff`).

You're right, it does not run in a cloned environment - at least not necessarily. I wrote the note with `alloacteEff` in mind and there the release action is run in a cloned environment. I updated the note to be a bit clearer on that.

> 
> Also, is having `es` and `es'` correct here? Does it make sense to be able to run the returned action in a completely different stack?

Yes, I think it makes sense. Consider the use case mentioned in the documentation of the `unprotect`:

> Unprotect resource from cleanup actions; this allows you to send resource into another resourcet process and reregister it there.

We don't now what the effect row of that other resourcet process looks like and it might (and probably will) be different from the one we are in when calling `unprotectEff`.

File: src/Effectful/Resource.hs [hunk 2]
```diff
@@ -100,6 +106,22 @@ registerEff release = do
...
+releaseEff :: Resource :> es => R.ReleaseKey -> Eff es ()
+releaseEff = unsafeEff_ . R.release
+
+-- | A variant of 'R.unprotect' adjusted to work in the 'Eff' monad.
+--
+-- /Note:/ if the resource was acquired using 'allocateEff', 'allocateEff_' or
+-- 'registerEff' then the @release@ action returned will run in a clone of the
+-- environment it was registered in, so the effect row @es'@ will be ignored.
+-- Please see the documentation of the aforementioned functions.
+unprotectEff
```
Comment (arybczak) [inline src/Effectful/Resource.hs]: I'm not necessarily convinced about this one.

One issue is that IIUC any invocation of this function without indicating what `es'` is will result in a compilation error about ambiguous type.

I think a signature `unprotectEff :: Resource :> es => R.ReleaseKey -> Eff es (Maybe (IO ()))` would be more reasonable here :thinking: Thoughts?

Comment (mmhat) [reply src/Effectful/Resource.hs]: > One issue is that IIUC any invocation of this function without indicating what `es'` is will result in a compilation error about ambiguous type.

I am afraid I don't understand what you mean. The following compiles just fine:
```haskell
{-# LANGUAGE FlexibleContexts #-}
{-# LANGUAGE TypeOperators #-}

module Main (main) where

import Data.Maybe (fromMaybe)
import Effectful
import Effectful.Dispatch.Static (unsafeEff_)
import Effectful.Resource

main :: IO ()
main = runEff . runResource $ do
    releaseMe <- myUnprotected
    fromMaybe (pure ()) releaseMe

myUnprotected :: (Resource :> es, Resource :> es') => Eff es (Maybe (Eff es' ()))
myUnprotected = do
    (key, _) <- myAllocation
    unprotectEff key

myAllocation :: (Resource :> es) => Eff es (ReleaseKey, ())
myAllocation =
    allocateEff
        (unsafeEff_ $ putStrLn "Allocating")
        (\_ -> unsafeEff_ $ putStrLn "Releasing")
```

> 
> I think a signature `unprotectEff :: Resource :> es => R.ReleaseKey -> Eff es (Maybe (IO ()))` would be more reasonable here 🤔 Thoughts?

I tried to avoid the `IO` action because the consuming side has to use either `liftIO` which introduces an unnecessary `IOE :> es` constraint or `unsafeEff_` which is also not ideal.
With the `Resource :> es'` constraint it is clear from the type signature of the consuming function that some resource handling is involved.
One other alternative I came up with is returning a `Eff '[Resource] ()`. Then the consumer can use that with `inject`. It works, but it's not really elegant.

That was at least the idea behind that implementation; If you're still not convinced I am fine with changing that.

Comment (arybczak) [reply src/Effectful/Resource.hs]: > I am afraid I don't understand what you mean. The following compiles just fine:

Yeah, because you're immediately using the `releaseMe` in the same effect stack, so GHC unifies `es` with `es'` and it all works out.

Now, see what happens if you replace `fromMaybe (pure ()) releaseMe` with `pure ()`, i.e. leave `releaseMe` unused:

```
    • Ambiguous type variable ‘es'0’ arising from a use of ‘myUnprotected’
      prevents the constraint ‘(Resource :> es'0)’ from being solved.
      Probable fix: use a type annotation to specify what ‘es'0’ should be.
      Potentially matching instances:
        instance [overlapping] e :> (e : es)
          -- Defined in ‘Effectful.Internal.Effect’
        instance (e :> es) => e :> (x : es)
          -- Defined in ‘Effectful.Internal.Effect’
        ...plus one other
        (use -fprint-potential-instances to see them all)
    • In a stmt of a 'do' block: releaseMe <- myUnprotected
      In the second argument of ‘($)’, namely
        ‘do releaseMe <- myUnprotected
            pure ()’
      In the expression:
        runEff . runResource
          $ do releaseMe <- myUnprotected
               pure ()
    |
162 |   releaseMe <- myUnprotected
    |                ^^^^^^^^^^^^^
```

> One other alternative I came up with is returning a Eff '[Resource] (). Then the consumer can use that with inject. It works, but it's not really elegant.

Yeah, this is better, but not very elegant as you say.

I don't really know what the best solution is to this issue and I don't want to delay this PR any further, so let's maybe agree to leave out `unprotectEff` for now from it? Then I can merge it and make a release and we can tackle the problem of `unprotectEff` separately.

Comment (mmhat) [reply src/Effectful/Resource.hs]: Ah, ok, now I get what you meant! Yes, I agree that this might not lead to the best user experience.

> I don't really know what the best solution is to this issue and I don't want to delay this PR any further, so let's maybe agree to leave out `unprotectEff` for now from it? Then I can merge it and make a release and we can tackle the problem of `unprotectEff` separately.

Agreed. I'll move the `unprotectEff` to a separate PR :+1:
